### PR TITLE
Translated isAlpha()

### PR DESCRIPTION
**Pull request by robsoncouto**
There seems to be something wrong with the example code tough.
It seems to be testing is a variable is alpha, but says to the user that is is alphanumeric.
May need fixing.

### CODE REVIEW

**Comment by smellai** [comment]
you are right @robsoncouto, I'll open an issue about that in the -en repo

**Comment by robsoncouto** [comment]
No problem :) 
I noticed there is something similar in https://cdn.arduino.cc/reference/en/language/functions/characters/isdigit/
The comment say "tests if this is a letter"  when it tests if the variable is a number. I fixed that one already here, as the problem was in the comment, not the code itself.
There may be other bugs like this in the other character functions I have not translated yet.

**Comment by smellai** [comment]
Fixed here: https://github.com/arduino/reference-en/commit/292bcc07365db42983b4d42211c12d7fef265d66

Please check the last commits in reference-en, we fixed many broken links. If, when you translate a page, you could check if all the links in the page are ok, it would be really great. Thanks so much

**Comment by robsoncouto** [comment]
Hi @smellai . I find it quite hard to keep focused in the translation and fix the broken links at the same time. For now I will keep up the translation and add an issue for the broken links.

**Pull request merged**
